### ISSUE TITLE
Earlier Umbraco versions

### ISSUE THREAD

**Issue by NikRimington** [yawkale/missingcode-umbraco-html-minifier#2]
Hi,

Is there a way to get your package to work with Umbraco 7.5? It doesn't have the IDiscoverable interface available so I was wondering what you use it for?

Cheers,

Nik

**Comment by yawkale** [comment]
Hi,
sorry for slow response, we upload version 0.9.5 for Umbraco 7.5, you can download from nuget https://www.nuget.org/packages/MissingCode.Umbraco.HtmlMinifier/0.9.5
