### ISSUE TITLE
Will there be an Umbraco 8 version of this package?

### ISSUE THREAD

**Issue by lcichanowicz** [yawkale/missingcode-umbraco-html-minifier#4]
Hi, @yawkale.  Will you be updating this package for Umbraco 8?  If you upload the source code here, I will attempt to update the package for Umbraco 8.

Thanks,
Lee

**Comment by yawkale** [comment]
Hi,
I'm planning to work on it next week, I'll update when it done

**Comment by yawkale** [comment]
fixed  - version 1.0.1 is for Umbraco v8
